/**
 * Background worker for Stage 12/69 — the "Plot" screen edit-by-prompt ("What to change in the plot").
 *
 * The old flow ran the whole-season prose rewrite synchronously inside the route (client held an open
 * fetch, no progress bar) and only the affected-episode SCRIPT rewrite happened in the background. This
 * worker moves the ENTIRE operation into a resumable GenerationJob (type "story_revise") so the client
 * sees a smooth 0→100 % bar for the prose rewrite + structure sync, then follows the handed-off season
 * job for the affected-episode script rewrite.
 *
 * The prompt-building / structure-diff logic lives in lib/season.ts and is NOT changed here.
 */
import { prisma } from "@/lib/db";
import { chatJSON } from "@/lib/ai";
import { updateJob, completeJob, failJob, isCancelRequested, markCanceled } from "@/lib/jobs";
import { maxDetailLevel } from "@/lib/location-scale";
import { toCharacterCard, normalizeLanguage } from "@/lib/idea";
import { runSeasonScriptJob, SEASON_JOB_TYPE, outlineFromEpisode } from "@/lib/workers/season-script-job";
import {
  seasonStoryReviseSchema,
  validateEpisodeSynopses,
  EPISODE_SYNOPSIS_RETRY_NOTE,
  seasonStoryReviseSystemPrompt,
  seasonStoryReviseUserPrompt,
  affectedEpisodes,
  matchLocation,
  SEASON_MIN_EPISODES,
  SEASON_MAX_EPISODES,
  type SeasonStructure,
  buildFullStoryFromStructure,
} from "@/lib/season";
import { repairEpisodeSynopses } from "../footage-repair";

/** GenerationJob.type value for the whole-season story rewrite. */
export const STORY_REVISE_JOB_TYPE = "story_revise";

/** Roughly how long the prose rewrite + structure sync takes — drives the smooth 0→100 % client bar. */
export const STORY_REVISE_EXPECTED_SEC = 90;

export interface StoryReviseParams {
  instruction: string;
  force?: boolean;
}

/**
 * Rewrite the whole-season prose story and keep the episode structure in sync (episodes may be
 * added/removed). Only episodes whose logline / arc / location / cast changed lose their script and
 * are regenerated by the resumable season job — already-generated episodes/assets are left intact.
 *
 * If an affected/removed episode already has generated video and force is not set, the job COMPLETES
 * with { needsForce, withVideo, episodes } and makes NO database change — the client then re-submits
 * with force=true after confirmation.
 */
export async function runStoryReviseJob(jobId: string, projectId: string, params: StoryReviseParams): Promise<void> {
  try {
    const instruction = (params.instruction ?? "").trim();
    const force = params.force === true;
    if (instruction.length < 3) { await failJob(jobId, "Describe what to change in the plot"); return; }

    if (await isCancelRequested(jobId)) { await markCanceled(jobId); return; }
    await updateJob(jobId, { status: "processing", progress: 8, message: "Rewriting season plot…" });

    const project = await prisma.project.findFirst({
      where: { id: projectId },
      include: { characters: true, locations: { orderBy: { createdAt: "asc" } } },
    });
    if (!project?.synopsis) { await failJob(jobId, "Project not found"); return; }

    const season = await prisma.season.findFirst({
      where: { projectId, number: 1 },
      include: { episodes: { orderBy: { number: "asc" }, include: { characters: { include: { character: true } }, scenes: { select: { videoUrl: true } }, location: { select: { detailLevel: true } } } } },
    });
    if (!season || season.episodes.length === 0) { await failJob(jobId, "First generate the season"); return; }

    const language = normalizeLanguage(project.language, project.synopsis);
    const cards = project.characters.map(toCharacterCard);
    const before: SeasonStructure = { title: season.title ?? "", logline: season.logline ?? "", episodes: season.episodes.map(outlineFromEpisode) };

    let after: SeasonStructure;
    let fullStory: string;
    try {
      // Stage 105 — the previous cliffhangers are passed as hard givens (cliffhangerChainGivens inside the user
      // prompt); descriptions are validated (3-line footage, ≤ 120 words, OPENS ON chain) and the call is
      // retried ONCE with an explicit format note — never truncated silently.
      const userPrompt = seasonStoryReviseUserPrompt({ synopsis: project.synopsis, structure: before, fullStory: season.fullStory ?? "", characters: cards, locations: project.locations, instruction });
      const attempt = async (note: string, strict: boolean) => {
        const raw = await chatJSON(seasonStoryReviseSystemPrompt(language, before.episodes.length), userPrompt + note, { temperature: 0.5, maxTokens: 16000 });
        const parsed = seasonStoryReviseSchema.parse(raw);
        if (parsed.episodes.length < SEASON_MIN_EPISODES || parsed.episodes.length > SEASON_MAX_EPISODES) throw new Error(`LLM returned ${parsed.episodes.length} episodes (allowed ${SEASON_MIN_EPISODES}–${SEASON_MAX_EPISODES})`);
        const episodes = parsed.episodes.map((e, i) => ({ ...e, number: i + 1 }));
        const problems = strict ? validateEpisodeSynopses(episodes) : [];
        if (problems.length) throw new Error(`episode descriptions need repair: ${problems.slice(0, 4).join("; ")}`);
        return { title: parsed.title, logline: parsed.logline, episodes, fullStory: parsed.fullStory.trim() };
      };
      let result: Awaited<ReturnType<typeof attempt>>;
      try {
        result = await attempt("", true);
      } catch (first) {
        const why = first instanceof Error ? first.message : String(first);
        console.warn(`[story-revise] first attempt rejected (${why}) — retrying once with the format note`);
        result = await attempt(`\n\n${EPISODE_SYNOPSIS_RETRY_NOTE} Problems found: ${why}`, false);
      }
      // Stage 128 — the retry's leftovers are repaired (targeted LLM passes) and finally clamped: never fail on format.
      const fixed = await repairEpisodeSynopses(result.episodes, language, (sys, usr) => chatJSON(sys, usr, { temperature: 0.3, maxTokens: 6000 }));
      if (fixed.repaired.length || fixed.clamped.length) console.warn(`[story-revise] synopsis repaired for episodes ${fixed.repaired.join(", ") || "-"}; clamped ${fixed.clamped.join(", ") || "-"}`);
      after = { title: result.title, logline: result.logline, episodes: fixed.episodes };
      // Stage 106 — the model's "fullStory" is ignored: the season plot is rebuilt from the validated structure
      // so the text and the episodes can never diverge.
      void result.fullStory;
      fullStory = buildFullStoryFromStructure(after, language, project.synopsis);
    } catch (err) {
      await failJob(jobId, "Failed to rewrite plot: " + (err instanceof Error ? err.message : String(err)));
      return;
    }

    if (await isCancelRequested(jobId)) { await markCanceled(jobId); return; }
    await updateJob(jobId, { progress: 45, message: "Syncing episode structure…" });

    const oldCount = before.episodes.length;
    const newCount = after.episodes.length;
    const affected = affectedEpisodes(before, after); // new + changed episodes → scripts regenerated
    const removedNumbers = oldCount > newCount ? season.episodes.filter((e) => e.number > newCount).map((e) => e.number) : [];

    // Episodes that will lose their scenes/video: changed survivors + removed ones.
    const rewritten = new Set<number>([...affected, ...removedNumbers]);
    const withVideo = season.episodes.filter((e) => rewritten.has(e.number) && e.scenes.some((s) => s.videoUrl)).map((e) => e.number);
    if (withVideo.length && !force) {
      await completeJob(jobId, {
        needsForce: true,
        episodes: [...rewritten].sort((a, b) => a - b),
        withVideo,
        error: `In episodes ${withVideo.join(", ")} already have generated video — editing will overwrite the scenes and videos for these episodes.`,
      }, "Confirmation required");
      return;
    }

    const byName = new Map(project.characters.map((c) => [c.name.toLowerCase(), c.id]));
    const locs: { id: string; name: string; detailLevel: string | null }[] = project.locations.map((l) => ({ id: l.id, name: l.name, detailLevel: l.detailLevel }));
    await prisma.$transaction(async (tx) => {
      await tx.season.update({ where: { id: season.id }, data: { title: after.title, logline: after.logline, fullStory } });
      if (removedNumbers.length) await tx.episode.deleteMany({ where: { seasonId: season.id, number: { in: removedNumbers } } }); // cascades scenes
      for (const e of after.episodes) {
        let loc = matchLocation(locs, e.locationName);
        if (!loc) {
          const created = await tx.location.create({ data: { projectId, name: e.locationName, description: e.locationName, visualPrompt: e.locationDesc, detailLevel: e.locationDetail } });
          loc = { id: created.id, name: created.name, detailLevel: created.detailLevel }; locs.push(loc);
        } else {
          // Reused location: raise its required detail level if the new structure needs more (never downgrade).
          const level = maxDetailLevel(loc.detailLevel, e.locationDetail);
          if (level && level !== loc.detailLevel) { await tx.location.update({ where: { id: loc.id }, data: { detailLevel: level } }); loc.detailLevel = level; }
        }
        const ep = season.episodes.find((x) => x.number === e.number);
        const ids = Array.from(new Set(e.characters.map((n) => byName.get(n.toLowerCase())).filter((x): x is string => !!x)));
        if (!ep) {
          // New episode (count increased) — created as a draft; its script is written by the season job below.
          const created = await tx.episode.create({ data: { seasonId: season.id, number: e.number, title: e.title, description: e.description ?? e.logline, logline: e.logline, cliffhanger: e.cliffhanger, locationName: loc.name, locationDesc: e.locationDesc, locationId: loc.id, arcRole: e.arcRole, status: "draft" } });
          if (ids.length) await tx.episodeCharacter.createMany({ data: ids.map((characterId) => ({ episodeId: created.id, characterId })), skipDuplicates: true });
          continue;
        }
        const rewrite = affected.includes(e.number);
        await tx.episode.update({
          where: { id: ep.id },
          data: {
            title: e.title, description: e.description ?? e.logline, logline: e.logline, cliffhanger: e.cliffhanger, locationName: loc.name, locationDesc: e.locationDesc, locationId: loc.id, arcRole: e.arcRole,
            ...(rewrite ? { script: null, status: "draft", videoUrl: null } : {}),
          },
        });
        await tx.episodeCharacter.deleteMany({ where: { episodeId: ep.id } });
        if (ids.length) await tx.episodeCharacter.createMany({ data: ids.map((characterId) => ({ episodeId: ep.id, characterId })), skipDuplicates: true });
        if (rewrite) await tx.scene.deleteMany({ where: { episodeId: ep.id } });
      }
    }, { timeout: 30_000 });

    // No episode needs a script rewrite → the whole operation is done.
    if (affected.length === 0) {
      await completeJob(jobId, { affected: [], removed: removedNumbers, episodeCount: newCount, done: true }, "Plot updated");
      return;
    }

    // Hand off the affected-episode script rewrite to the resumable season job. The season job's first
    // advance is quick (it starts an OpenAI background response and saves state); the client then follows
    // that job's id for the episode-rewrite progress bar. Await directly (we are already in a background
    // context) so the first tick runs before we complete this job.
    const seasonJob = await prisma.generationJob.create({
      data: { type: SEASON_JOB_TYPE, status: "pending", progress: 0, message: `Rewriting episodes ${affected.join(", ")}...`, projectId, resultData: JSON.stringify({ revise: true, affected }) },
    });
    await runSeasonScriptJob(seasonJob.id, projectId, newCount);
    await completeJob(jobId, { affected, removed: removedNumbers, episodeCount: newCount, seasonJobId: seasonJob.id, done: true }, `Rewriting episodes ${affected.join(", ")}...`);
  } catch (err: any) {
    console.error("[story-revise] job error:", err);
    await failJob(jobId, "Generation failed: " + (err?.message ?? "Unknown error"));
  }
}
