var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/project/new/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0vrz1mt._.js")
R.c("server/chunks/ssr/home_ubuntu_github_repos_Foltum-Studio-WEB_1m-orz3._.js")
R.c("server/chunks/ssr/1qjk_next_dist_1ffe5d0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ic75b2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p35caj._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1vo3_-f._.js")
R.c("server/chunks/ssr/1qjk_next_dist_client_components_1vwq-u0._.js")
R.c("server/chunks/ssr/1qjk_next_dist_client_components_builtin_forbidden_1jwsn09.js")
R.c("server/chunks/ssr/1qjk_next_dist_client_components_builtin_unauthorized_017m5b6.js")
R.c("server/chunks/ssr/1qjk_next_dist_client_components_builtin_global-error_0mj-r3t.js")
R.c("server/chunks/ssr/1622_Foltum-Studio-WEB__next-internal_server_app_project_new_page_actions_00ff79d.js")
R.m(86405)
module.exports=R.m(86405).exports
