export const dynamic = "force-dynamic";
export const maxDuration = 800; // the season job (rewriting affected episodes) runs in the background via after()

import { NextResponse } from "next/server";
import { maxDetailLevel } from "@/lib/location-scale";
import { auth } from "@/auth";
import { prisma } from "@/lib/db";
import { chatJSON } from "@/lib/ai";
import { rateLimitByUser, RATE_LIMITS } from "@/lib/rate-limit";
import { runInBackground, failStaleJobs } from "@/lib/jobs";
import { toCharacterCard, normalizeLanguage } from "@/lib/idea";
import { runSeasonScriptJob, SEASON_JOB_TYPE, outlineFromEpisode } from "@/lib/workers/season-script-job";
import { seasonReviseSchema, seasonReviseSystemPrompt, seasonReviseUserPrompt, affectedEpisodes, matchLocation, SEASON_SYNC_INSTRUCTION, type SeasonStructure } from "@/lib/season";

/**
 * POST /api/ai/season/revise { projectId, instruction?, sync?, force? }
 * Stage 5 — season-level prompt editing. The LLM rewrites the season structure by the instruction
 * (minimal change), the Episode rows are updated, and the episodes whose logline / arc / location /
 * cast changed lose their script and are regenerated by the same resumable season job.
 * If an affected episode already has generated video → 409 { needsForce, episodes } unless force=true.
 * Returns { jobId | null, affected: number[] }.
 */
export async function POST(request: Request) {
  const session = await auth();
  if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const limited = await rateLimitByUser(request, "ai-season-revise", session.user.email ?? session.user.id, RATE_LIMITS.ai);
  if (limited) return limited;

  const body = await request.json().catch(() => ({}));
  const projectId = String(body?.projectId ?? "");
  const sync = body?.sync === true;
  const instruction = sync ? SEASON_SYNC_INSTRUCTION : String(body?.instruction ?? "").trim();
  const force = body?.force === true;
  if (!projectId) return NextResponse.json({ error: "projectId required" }, { status: 400 });
  if (instruction.length < 3) return NextResponse.json({ error: "Describe what to change in the season" }, { status: 400 });

  const project = await prisma.project.findFirst({ where: { id: projectId, userId: session.user.id }, include: { characters: true, locations: { orderBy: { createdAt: "asc" } } } });
  if (!project?.synopsis) return NextResponse.json({ error: "Project not found" }, { status: 404 });

  await failStaleJobs({ projectId, type: SEASON_JOB_TYPE });
  const active = await prisma.generationJob.findFirst({ where: { projectId, type: SEASON_JOB_TYPE, status: { in: ["pending", "processing"] } } });
  if (active) return NextResponse.json({ error: "The season script is still being written — wait until it finishes, then edit the season." }, { status: 409 });

  const season = await prisma.season.findFirst({
    where: { projectId, number: 1 },
    include: { episodes: { orderBy: { number: "asc" }, include: { characters: { include: { character: true } }, scenes: { select: { videoUrl: true } }, location: { select: { detailLevel: true } } } } },
  });
  if (!season || season.episodes.length === 0) return NextResponse.json({ error: "First generate the season script" }, { status: 400 });

  const language = normalizeLanguage(project.language, project.synopsis);
  const cards = project.characters.map(toCharacterCard);
  const before: SeasonStructure = { title: season.title ?? "", logline: season.logline ?? "", episodes: season.episodes.map(outlineFromEpisode) };

  let after: SeasonStructure;
  try {
    const raw = await chatJSON(seasonReviseSystemPrompt(language, before.episodes.length), seasonReviseUserPrompt({ synopsis: project.synopsis, structure: before, characters: cards, locations: project.locations, instruction }), { temperature: 0.4, maxTokens: 6000 });
    const parsed = seasonReviseSchema.parse(raw);
    if (parsed.episodes.length !== before.episodes.length) throw new Error(`LLM returned ${parsed.episodes.length} episodes instead of ${before.episodes.length}`);
    after = { ...parsed, episodes: parsed.episodes.map((e, i) => ({ ...e, number: i + 1 })) };
  } catch (err) {
    return NextResponse.json({ error: "Failed to rebuild season: " + (err instanceof Error ? err.message : String(err)) }, { status: 502 });
  }

  const affected = affectedEpisodes(before, after);
  const withVideo = season.episodes.filter((e) => affected.includes(e.number) && e.scenes.some((s) => s.videoUrl)).map((e) => e.number);
  if (withVideo.length && !force) {
    return NextResponse.json({
      error: `In episodes ${withVideo.join(", ")} already have generated video — when rewriting, the scenes and videos for these episodes will be deleted.`,
      needsForce: true, episodes: affected, withVideo,
    }, { status: 409 });
  }

  const byName = new Map(project.characters.map((c) => [c.name.toLowerCase(), c.id]));
  const locs: { id: string; name: string; detailLevel: string | null }[] = project.locations.map((l) => ({ id: l.id, name: l.name, detailLevel: l.detailLevel }));
  await prisma.$transaction(async (tx) => {
    await tx.season.update({ where: { id: season.id }, data: { title: after.title, logline: after.logline } });
    for (const e of after.episodes) {
      const ep = season.episodes.find((x) => x.number === e.number);
      if (!ep) continue;
      let loc = matchLocation(locs, e.locationName);
      if (!loc) {
        const created = await tx.location.create({ data: { projectId, name: e.locationName, description: e.locationName, visualPrompt: e.locationDesc, visualPromptAuto: e.locationDesc, detailLevel: e.locationDetail } });
        loc = { id: created.id, name: created.name, detailLevel: created.detailLevel }; locs.push(loc);
      } else {
        // Reused location: raise its required detail level if the new structure needs more (never downgrade).
        const level = maxDetailLevel(loc.detailLevel, e.locationDetail);
        if (level && level !== loc.detailLevel) { await tx.location.update({ where: { id: loc.id }, data: { detailLevel: level } }); loc.detailLevel = level; }
      }
      const rewrite = affected.includes(e.number);
      await tx.episode.update({
        where: { id: ep.id },
        data: {
          title: e.title, description: e.logline, logline: e.logline, cliffhanger: e.cliffhanger, locationName: loc.name, locationDesc: e.locationDesc, locationId: loc.id, arcRole: e.arcRole,
          ...(rewrite ? { script: null, status: "draft", videoUrl: null } : {}),
        },
      });
      const ids = Array.from(new Set(e.characters.map((n) => byName.get(n.toLowerCase())).filter((x): x is string => !!x)));
      await tx.episodeCharacter.deleteMany({ where: { episodeId: ep.id } });
      if (ids.length) await tx.episodeCharacter.createMany({ data: ids.map((characterId) => ({ episodeId: ep.id, characterId })), skipDuplicates: true });
      if (rewrite) await tx.scene.deleteMany({ where: { episodeId: ep.id } });
    }
  }, { timeout: 30_000 });

  if (affected.length === 0) return NextResponse.json({ jobId: null, affected, title: after.title });

  const job = await prisma.generationJob.create({ data: { type: SEASON_JOB_TYPE, status: "pending", progress: 0, message: `Rewriting episodes ${affected.join(", ")}...`, projectId, resultData: JSON.stringify({ revise: true, affected }) } });
  runInBackground(() => runSeasonScriptJob(job.id, projectId, before.episodes.length));
  return NextResponse.json({ jobId: job.id, affected, title: after.title });
}
