export const dynamic = "force-dynamic";
export const maxDuration = 800; // the story LLM call runs here; affected-episode scripts are rewritten in the background via after()

import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { prisma } from "@/lib/db";
import { chatJSON } from "@/lib/ai";
import { rateLimitByUser, RATE_LIMITS } from "@/lib/rate-limit";
import { runInBackground, failStaleJobs } from "@/lib/jobs";
import { toCharacterCard, normalizeLanguage } from "@/lib/idea";
import { runSeasonScriptJob, SEASON_JOB_TYPE, outlineFromEpisode } from "@/lib/workers/season-script-job";
import {
  seasonStoryReviseSchema,
  seasonStoryReviseSystemPrompt,
  seasonStoryReviseUserPrompt,
  affectedEpisodes,
  matchLocation,
  countFullStoryEpisodes,
  SEASON_MIN_EPISODES,
  SEASON_MAX_EPISODES,
  type SeasonStructure,
} from "@/lib/season";

/**
 * POST /api/ai/season/full-story/revise { projectId, instruction, force? }
 * Stage 12 — the "Сюжет" screen edit-by-prompt. The LLM rewrites the whole-season prose story AND
 * keeps the episode structure in sync (the author may add/remove episodes — count may change).
 * MINIMAL CHANGE: only episodes whose logline / arc / location / cast changed lose their script and
 * are regenerated by the resumable season job — already-generated episodes/assets are otherwise left intact.
 * If an affected or removed episode already has generated video → 409 { needsForce, withVideo } unless force=true.
 * Returns { jobId | null, affected: number[], episodeCount, fullStory }.
 */
export async function POST(request: Request) {
  const session = await auth();
  if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const limited = await rateLimitByUser(request, "ai-season-story-revise", session.user.email ?? session.user.id, RATE_LIMITS.ai);
  if (limited) return limited;

  const body = await request.json().catch(() => ({}));
  const projectId = String(body?.projectId ?? "");
  const instruction = String(body?.instruction ?? "").trim();
  const force = body?.force === true;
  if (!projectId) return NextResponse.json({ error: "projectId required" }, { status: 400 });
  if (instruction.length < 3) return NextResponse.json({ error: "Опишите, что изменить в сюжете" }, { status: 400 });

  const project = await prisma.project.findFirst({ where: { id: projectId, userId: session.user.id }, include: { characters: true, locations: { orderBy: { createdAt: "asc" } } } });
  if (!project?.synopsis) return NextResponse.json({ error: "Project not found" }, { status: 404 });

  await failStaleJobs({ projectId, type: SEASON_JOB_TYPE });
  const active = await prisma.generationJob.findFirst({ where: { projectId, type: SEASON_JOB_TYPE, status: { in: ["pending", "processing"] } } });
  if (active) return NextResponse.json({ error: "Сюжет сезона ещё пишется — дождитесь окончания, затем внесите правки." }, { status: 409 });

  const season = await prisma.season.findFirst({
    where: { projectId, number: 1 },
    include: { episodes: { orderBy: { number: "asc" }, include: { characters: { include: { character: true } }, scenes: { select: { videoUrl: true } } } } },
  });
  if (!season || season.episodes.length === 0) return NextResponse.json({ error: "Сначала сгенерируйте сезон" }, { status: 400 });

  const language = normalizeLanguage(project.language, project.synopsis);
  const cards = project.characters.map(toCharacterCard);
  const before: SeasonStructure = { title: season.title ?? "", logline: season.logline ?? "", episodes: season.episodes.map(outlineFromEpisode) };

  let after: SeasonStructure;
  let fullStory: string;
  try {
    const raw = await chatJSON(
      seasonStoryReviseSystemPrompt(language, before.episodes.length),
      seasonStoryReviseUserPrompt({ synopsis: project.synopsis, structure: before, fullStory: season.fullStory ?? "", characters: cards, locations: project.locations, instruction }),
      { temperature: 0.5, maxTokens: 20000 }
    );
    const parsed = seasonStoryReviseSchema.parse(raw);
    if (parsed.episodes.length < SEASON_MIN_EPISODES || parsed.episodes.length > SEASON_MAX_EPISODES) throw new Error(`LLM вернул ${parsed.episodes.length} эпизодов (допустимо ${SEASON_MIN_EPISODES}–${SEASON_MAX_EPISODES})`);
    after = { title: parsed.title, logline: parsed.logline, episodes: parsed.episodes.map((e, i) => ({ ...e, number: i + 1 })) };
    fullStory = parsed.fullStory.trim();
  } catch (err) {
    return NextResponse.json({ error: "Не удалось переписать сюжет: " + (err instanceof Error ? err.message : String(err)) }, { status: 502 });
  }

  const oldCount = before.episodes.length;
  const newCount = after.episodes.length;
  const affected = affectedEpisodes(before, after); // new + changed episodes → scripts regenerated
  const removedNumbers = oldCount > newCount ? season.episodes.filter((e) => e.number > newCount).map((e) => e.number) : [];

  // Episodes that will lose their scenes/video: changed survivors + removed ones.
  const rewritten = new Set<number>([...affected, ...removedNumbers]);
  const withVideo = season.episodes.filter((e) => rewritten.has(e.number) && e.scenes.some((s) => s.videoUrl)).map((e) => e.number);
  if (withVideo.length && !force) {
    return NextResponse.json({
      error: `В эпизодах ${withVideo.join(", ")} уже есть сгенерированное видео — правка перепишет сцены и видео этих эпизодов.`,
      needsForce: true, episodes: [...rewritten].sort((a, b) => a - b), withVideo,
    }, { status: 409 });
  }

  const byName = new Map(project.characters.map((c) => [c.name.toLowerCase(), c.id]));
  const locs: { id: string; name: string }[] = project.locations.map((l) => ({ id: l.id, name: l.name }));
  await prisma.$transaction(async (tx) => {
    await tx.season.update({ where: { id: season.id }, data: { title: after.title, logline: after.logline, fullStory } });
    if (removedNumbers.length) await tx.episode.deleteMany({ where: { seasonId: season.id, number: { in: removedNumbers } } }); // cascades scenes
    for (const e of after.episodes) {
      let loc = matchLocation(locs, e.locationName);
      if (!loc) {
        const created = await tx.location.create({ data: { projectId, name: e.locationName, description: e.locationName, visualPrompt: e.locationDesc } });
        loc = { id: created.id, name: created.name }; locs.push(loc);
      }
      const ep = season.episodes.find((x) => x.number === e.number);
      const ids = Array.from(new Set(e.characters.map((n) => byName.get(n.toLowerCase())).filter((x): x is string => !!x)));
      if (!ep) {
        // New episode (count increased) — created as a draft; its script is written by the season job below.
        const created = await tx.episode.create({ data: { seasonId: season.id, number: e.number, title: e.title, description: e.logline, logline: e.logline, cliffhanger: e.cliffhanger, locationName: loc.name, locationDesc: e.locationDesc, locationId: loc.id, arcRole: e.arcRole, status: "draft" } });
        if (ids.length) await tx.episodeCharacter.createMany({ data: ids.map((characterId) => ({ episodeId: created.id, characterId })), skipDuplicates: true });
        continue;
      }
      const rewrite = affected.includes(e.number);
      await tx.episode.update({
        where: { id: ep.id },
        data: {
          title: e.title, description: e.logline, logline: e.logline, cliffhanger: e.cliffhanger, locationName: loc.name, locationDesc: e.locationDesc, locationId: loc.id, arcRole: e.arcRole,
          ...(rewrite ? { script: null, status: "draft", videoUrl: null } : {}),
        },
      });
      await tx.episodeCharacter.deleteMany({ where: { episodeId: ep.id } });
      if (ids.length) await tx.episodeCharacter.createMany({ data: ids.map((characterId) => ({ episodeId: ep.id, characterId })), skipDuplicates: true });
      if (rewrite) await tx.scene.deleteMany({ where: { episodeId: ep.id } });
    }
  }, { timeout: 30_000 });

  if (affected.length === 0) return NextResponse.json({ jobId: null, affected, episodeCount: newCount, fullStory });

  const job = await prisma.generationJob.create({ data: { type: SEASON_JOB_TYPE, status: "pending", progress: 0, message: `Переписываю эпизоды ${affected.join(", ")}...`, projectId, resultData: JSON.stringify({ revise: true, affected }) } });
  runInBackground(() => runSeasonScriptJob(job.id, projectId, newCount));
  return NextResponse.json({ jobId: job.id, affected, episodeCount: newCount, fullStory });
}
