// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/login" | "/pricing" | "/project/[id]" | "/project/new" | "/signup"
type AppRouteHandlerRoutes = "/api/ai/accept-scene" | "/api/ai/assemble-episode" | "/api/ai/characters" | "/api/ai/characters/regenerate" | "/api/ai/generate-video" | "/api/ai/scenes" | "/api/ai/structure" | "/api/ai/synopsis" | "/api/auth/[...nextauth]" | "/api/auth/login" | "/api/credits/add" | "/api/projects" | "/api/projects/[id]" | "/api/projects/[id]/approve-structure" | "/api/projects/[id]/approve-synopsis" | "/api/projects/[id]/lock-characters" | "/api/signup" | "/api/upload/presigned" | "/api/user/credits"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/accept-scene": {}
  "/api/ai/assemble-episode": {}
  "/api/ai/characters": {}
  "/api/ai/characters/regenerate": {}
  "/api/ai/generate-video": {}
  "/api/ai/scenes": {}
  "/api/ai/structure": {}
  "/api/ai/synopsis": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/login": {}
  "/api/credits/add": {}
  "/api/projects": {}
  "/api/projects/[id]": { "id": string; }
  "/api/projects/[id]/approve-structure": { "id": string; }
  "/api/projects/[id]/approve-synopsis": { "id": string; }
  "/api/projects/[id]/lock-characters": { "id": string; }
  "/api/signup": {}
  "/api/upload/presigned": {}
  "/api/user/credits": {}
  "/dashboard": {}
  "/login": {}
  "/pricing": {}
  "/project/[id]": { "id": string; }
  "/project/new": {}
  "/signup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
