/**
 * Central registry of the AI models the producer can pick in the UI.
 *
 * IMPORTANT: only models that are ACTUALLY wired in lib/replicate.ts are listed here —
 * we never expose a model the backend can't run.
 *
 *  - Image references (characters + locations) are generated ONLY by Seedream 5.0 Lite
 *    (bytedance/seedream-5-lite → startImagePrediction / generateImage). It is the single
 *    real image model in the codebase, so the image picker currently has one entry; adding
 *    another model later means one line here + a branch in startImagePrediction.
 *  - Scene videos can be generated by two real models: Seedance 2.5 (native audio, default)
 *    and Kling v2.1 (silent image-to-video, capped at 10s). Both are already implemented in
 *    the video worker via the `provider` union ("seedance" | "kling"), so the video model id
 *    is exactly that provider string.
 */

/* ------------------------------- Image models ------------------------------- */

export const IMAGE_MODELS = [
  { id: "seedream-5-lite", label: "Seedream 5.0 Lite — фотореализм" },
] as const;

export type ImageModelId = (typeof IMAGE_MODELS)[number]["id"];

export const DEFAULT_IMAGE_MODEL: ImageModelId = "seedream-5-lite";

/** Coerce any incoming value to a known image model id (falls back to the default). */
export function normalizeImageModel(v: unknown): ImageModelId {
  return IMAGE_MODELS.some((m) => m.id === v) ? (v as ImageModelId) : DEFAULT_IMAGE_MODEL;
}

/* ------------------------------- Video models ------------------------------- */
/* The id doubles as the video worker `provider` value. */

export const VIDEO_MODELS = [
  { id: "seedance", label: "Seedance 2.5 — со звуком (по умолчанию)" },
  { id: "kling", label: "Kling v2.1 — без звука, image-to-video, до 10с" },
] as const;

export type VideoModelId = (typeof VIDEO_MODELS)[number]["id"];

export const DEFAULT_VIDEO_MODEL: VideoModelId = "seedance";

/** Coerce any incoming value to a known video model id / provider (falls back to the default). */
export function normalizeVideoModel(v: unknown): VideoModelId {
  return VIDEO_MODELS.some((m) => m.id === v) ? (v as VideoModelId) : DEFAULT_VIDEO_MODEL;
}
