/**
 * Central registry of the AI models the producer can pick in the UI.
 *
 * IMPORTANT: only models that are ACTUALLY wired in lib/replicate.ts are listed here —
 * we never expose a model the backend can't run.
 *
 *  - Image references (characters + locations) are generated ONLY by Seedream 5.0 Lite
 *    (bytedance/seedream-5-lite → startImagePrediction / generateImage). It is the single
 *    real image model in the codebase, so the image picker currently has one entry; adding
 *    another model later means one line here + a branch in startImagePrediction.
 *  - Scene videos can be generated by two real models, BOTH with synchronized native audio:
 *    Seedance 2.5 (default, up to 30s per clip) and Seedance 2.0 (up to 15s per clip). Both are
 *    implemented in the video worker via the `provider` union ("seedance" | "seedance-2.0"),
 *    so the video model id is exactly that provider string (mapped to the Replicate slug there).
 */

/* ------------------------------- Image models ------------------------------- */

export const IMAGE_MODELS = [
  { id: "seedream-5-lite", label: "Seedream 5.0 Lite — фотореализм" },
] as const;

export type ImageModelId = (typeof IMAGE_MODELS)[number]["id"];

export const DEFAULT_IMAGE_MODEL: ImageModelId = "seedream-5-lite";

/** Coerce any incoming value to a known image model id (falls back to the default). */
export function normalizeImageModel(v: unknown): ImageModelId {
  return IMAGE_MODELS.some((m) => m.id === v) ? (v as ImageModelId) : DEFAULT_IMAGE_MODEL;
}

/* ------------------------------- Video models ------------------------------- */
/* The id doubles as the video worker `provider` value. */

export const VIDEO_MODELS = [
  { id: "seedance", label: "Seedance 2.5 — со звуком (по умолчанию)" },
  { id: "seedance-2.0", label: "Seedance 2.0 — со звуком, до 15с" },
] as const;

export type VideoModelId = (typeof VIDEO_MODELS)[number]["id"];

export const DEFAULT_VIDEO_MODEL: VideoModelId = "seedance";

/** Coerce any incoming value to a known video model id / provider (falls back to the default). */
export function normalizeVideoModel(v: unknown): VideoModelId {
  return VIDEO_MODELS.some((m) => m.id === v) ? (v as VideoModelId) : DEFAULT_VIDEO_MODEL;
}

/**
 * Replicate slug for each video model id. Single source of truth shared by the video worker and
 * the prompt-preview builder so both submit / display the exact same model.
 */
export const VIDEO_MODEL_SLUGS: Record<VideoModelId, string> = {
  "seedance": "bytedance/seedance-2.5",
  "seedance-2.0": "bytedance/seedance-2.0",
};

/** Replicate slug for a (normalized) video model id. */
export function videoModelSlug(id: VideoModelId): string {
  return VIDEO_MODEL_SLUGS[id];
}
