/**
 * Central registry of the AI models wired into the backend.
 *
 * IMPORTANT: only models that are ACTUALLY wired in lib/replicate.ts are listed here —
 * we never expose a model the backend can't run.
 *
 *  - Image references (characters + locations) are generated ONLY by Seedream 5.0 Lite
 *    (bytedance/seedream-5-lite → startImagePrediction / generateImage). It is the single
 *    real image model in the codebase, so the image picker currently has one entry; adding
 *    another model later means one line here + a branch in startImagePrediction.
 *  - Scene videos are generated by ONE model: Seedance 2.5 (synchronized native audio, up to 30 s
 *    per clip). Stage 33 removed the user-facing model choice; the video model id doubles as the
 *    worker `provider` value and `normalizeVideoModel` maps ANY input (including legacy stored
 *    ids) to it.
 */

/* ------------------------------- Image models ------------------------------- */

export const IMAGE_MODELS = [
  { id: "seedream-5-lite", label: "Seedream 5.0 Lite — фотореализм" },
] as const;

export type ImageModelId = (typeof IMAGE_MODELS)[number]["id"];

export const DEFAULT_IMAGE_MODEL: ImageModelId = "seedream-5-lite";

/** Coerce any incoming value to a known image model id (falls back to the default). */
export function normalizeImageModel(v: unknown): ImageModelId {
  return IMAGE_MODELS.some((m) => m.id === v) ? (v as ImageModelId) : DEFAULT_IMAGE_MODEL;
}

/* ------------------------------- Video models ------------------------------- */
/* The id doubles as the video worker `provider` value. */

export const VIDEO_MODELS = [
  { id: "seedance", label: "Seedance 2.5 — со звуком" },
] as const;

export type VideoModelId = (typeof VIDEO_MODELS)[number]["id"];

export const DEFAULT_VIDEO_MODEL: VideoModelId = "seedance";

/** Human-readable label of the single video model (shown statically in the UI). */
export const VIDEO_MODEL_LABEL = "Seedance 2.5";

/**
 * Coerce any incoming value to the single video model id. Legacy rows may still store the retired
 * "seedance-2.0" id (or null / anything else) — every input resolves to Seedance 2.5.
 */
export function normalizeVideoModel(_v: unknown): VideoModelId {
  return DEFAULT_VIDEO_MODEL;
}

/**
 * Replicate slug for each video model id. Single source of truth shared by the video worker and
 * the prompt-preview builder so both submit / display the exact same model.
 */
export const VIDEO_MODEL_SLUGS: Record<VideoModelId, string> = {
  "seedance": "bytedance/seedance-2.5",
};

/** Replicate slug for a (normalized) video model id. */
export function videoModelSlug(id: VideoModelId): string {
  return VIDEO_MODEL_SLUGS[id] ?? VIDEO_MODEL_SLUGS[DEFAULT_VIDEO_MODEL];
}
