/**
 * Local ffmpeg helpers (server-side, via the `ffmpeg-static` binary).
 *
 * Used by episode assembly: every scene clip gets a UNIFORM audio track
 * (legacy separate audio if present, otherwise the clip's own audio, otherwise
 * silence), then all clips are concatenated. Doing this locally — instead of
 * through a remote ffmpeg model — guarantees the final file keeps its audio
 * stream; the previous remote concatenation silently dropped it.
 */
import { execFile } from "child_process";
import { promises as fs } from "fs";
import os from "os";
import path from "path";
import { promisify } from "util";

const execFileAsync = promisify(execFile);

/** Resolve the ffmpeg binary: env override → ffmpeg-static → PATH. */
function getFfmpegPath(): string {
  if (process.env.FFMPEG_PATH) return process.env.FFMPEG_PATH;
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const p = require("ffmpeg-static") as string | null;
    if (p) return p;
  } catch {
    /* fall through */
  }
  return "ffmpeg";
}

async function runFfmpeg(args: string[], label: string, opts?: { cwd?: string }): Promise<string> {
  const bin = getFfmpegPath();
  try {
    const { stderr } = await execFileAsync(bin, ["-hide_banner", "-nostdin", "-y", ...args], {
      maxBuffer: 32 * 1024 * 1024,
      timeout: 10 * 60 * 1000,
      ...(opts?.cwd ? { cwd: opts.cwd } : {}),
    });
    return stderr ?? "";
  } catch (err: any) {
    const tail = String(err?.stderr ?? err?.message ?? "").split("\n").slice(-12).join("\n");
    throw new Error(`ffmpeg ${label} failed: ${tail}`);
  }
}

/** Download a remote file to disk. */
export async function downloadToFile(url: string, dest: string): Promise<void> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to download ${url}: ${res.status}`);
  await fs.writeFile(dest, Buffer.from(await res.arrayBuffer()));
}

/**
 * Extract the LAST frame of a video as a JPEG buffer.
 *
 * Used for one-take frame-chaining: the last frame of scene N is fed to Seedance as the
 * first-frame (`image`) of scene N+1, so the next clip starts exactly where the previous
 * one ended and the whole episode reads as a single continuous take.
 *
 * `-sseof -1` seeks to the last second and `-update 1` keeps overwriting the output with
 * each decoded frame, so the file left on disk is the very last frame of the clip.
 */
export async function extractLastFrameBuffer(videoUrl: string): Promise<Buffer> {
  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), "lastframe-"));
  const videoPath = path.join(workDir, "src.mp4");
  const outPath = path.join(workDir, "last.jpg");
  try {
    await downloadToFile(videoUrl, videoPath);
    // Try the fast seek-from-end approach first.
    try {
      await runFfmpeg(
        ["-sseof", "-1", "-i", videoPath, "-update", "1", "-q:v", "2", "-frames:v", "1", outPath],
        "extract last frame (sseof)"
      );
    } catch {
      // Fallback: reverse the last chunk and grab its first frame.
      await runFfmpeg(
        ["-i", videoPath, "-vf", "reverse", "-q:v", "2", "-frames:v", "1", outPath],
        "extract last frame (reverse)"
      );
    }
    return await fs.readFile(outPath);
  } finally {
    await fs.rm(workDir, { recursive: true, force: true }).catch(() => {});
  }
}

/**
 * Download a video and extract its AUDIO track as a WAV buffer (PCM 16-bit,
 * 44.1kHz stereo — the format the lipsync model expects).
 *
 * Used by the realistic Kling+lipsync pipeline: the native speech generated by a
 * (moderation-passing) Seedance run is pulled out of that clip and fed to the
 * lipsync model on top of the silent Kling video. Throws a clear error if the
 * source clip has no audio stream, so the caller can surface it honestly.
 */
export async function extractAudioBuffer(videoUrl: string): Promise<Buffer> {
  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), "speech-"));
  const videoPath = path.join(workDir, "src.mp4");
  const outPath = path.join(workDir, "speech.wav");
  try {
    await downloadToFile(videoUrl, videoPath);
    const info = await probeMedia(videoPath);
    if (!info.hasAudio) throw new Error("Source clip has no audio stream to extract");
    await runFfmpeg(
      ["-i", videoPath, "-vn", "-acodec", "pcm_s16le", "-ar", "44100", "-ac", "2", outPath],
      "extract audio track"
    );
    return await fs.readFile(outPath);
  } finally {
    await fs.rm(workDir, { recursive: true, force: true }).catch(() => {});
  }
}

export interface MediaInfo {
  hasVideo: boolean;
  hasAudio: boolean;
  /** Container duration in seconds (0 if unknown). */
  duration: number;
  /** Video geometry / frame rate (0 if unknown). */
  width: number;
  height: number;
  fps: number;
}

/** Probe a media file using ffmpeg's `-i` listing (ffmpeg-static ships no ffprobe). */
export async function probeMedia(file: string): Promise<MediaInfo> {
  const bin = getFfmpegPath();
  let out = "";
  try {
    const { stderr } = await execFileAsync(bin, ["-hide_banner", "-nostdin", "-i", file], {
      maxBuffer: 8 * 1024 * 1024,
    });
    out = stderr ?? "";
  } catch (err: any) {
    // ffmpeg exits non-zero when no output is specified — the stream listing is still in stderr.
    out = String(err?.stderr ?? "");
  }
  const m = out.match(/Duration:\s*(\d+):(\d+):(\d+(?:\.\d+)?)/);
  const duration = m ? Number(m[1]) * 3600 + Number(m[2]) * 60 + Number(m[3]) : 0;
  const videoLine = out.match(/Stream #\d+:\d+.*?: Video:.*$/m)?.[0] ?? "";
  const dim = videoLine.match(/[ ,](\d{2,5})x(\d{2,5})(?:[ ,\[]|$)/);
  const fpsM = videoLine.match(/(\d+(?:\.\d+)?)\s*fps/);
  return {
    hasVideo: videoLine.length > 0,
    hasAudio: /Stream #\d+:\d+.*?: Audio:/.test(out),
    duration,
    width: dim ? Number(dim[1]) : 0,
    height: dim ? Number(dim[2]) : 0,
    fps: fpsM ? Number(fpsM[1]) : 0,
  };
}

export interface SceneClipInput {
  videoUrl: string;
  /** Separate voiceover (e.g. uploaded audio). Takes priority over the clip's own audio. */
  audioUrl?: string | null;
  /** Cleaned spoken text for this scene — burned in as a subtitle over the clip's segment. */
  subtitle?: string | null;
}

/* ------------------------------------------------------------------ */
/*  Subtitles                                                          */
/* ------------------------------------------------------------------ */

/** Format seconds as an SRT timestamp: HH:MM:SS,mmm */
function srtTime(sec: number): string {
  const s = Math.max(0, sec);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const ss = Math.floor(s % 60);
  const ms = Math.round((s - Math.floor(s)) * 1000);
  const p = (n: number, w = 2) => String(n).padStart(w, "0");
  return `${p(h)}:${p(m)}:${p(ss)},${p(ms, 3)}`;
}

/** Wrap a subtitle line to ~2 lines so it stays readable on a 9:16 frame. */
function wrapSubtitle(text: string, max = 38): string {
  const words = text.replace(/\s+/g, " ").trim().split(" ");
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    if ((cur + " " + w).trim().length > max && cur) {
      lines.push(cur);
      cur = w;
    } else {
      cur = (cur + " " + w).trim();
    }
  }
  if (cur) lines.push(cur);
  // Keep at most 2 lines; if longer, collapse the tail into the second line.
  if (lines.length > 2) return [lines[0], lines.slice(1).join(" ")].join("\n");
  return lines.join("\n");
}

/**
 * Build an SRT whose cues are timed to each clip's position on the FINAL timeline.
 * With a crossfade of `transition` seconds, clip i begins at
 *   start_i = start_{i-1} + dur_{i-1} - transition  (start_0 = 0)
 * The cue is shown for the fully-visible middle of the clip (skipping the fade in/out)
 * so text never overlaps a transition.
 */
function buildSrt(subtitles: (string | null | undefined)[], infos: MediaInfo[], transition: number): string {
  const t = infos.length > 1 ? transition : 0;
  const starts: number[] = [];
  let running = 0;
  for (let i = 0; i < infos.length; i++) {
    if (i === 0) starts.push(0);
    else {
      running = Math.max(0, running - t);
      starts.push(running);
    }
    running = starts[i] + (infos[i].duration || 0);
  }

  const cues: string[] = [];
  let idx = 1;
  for (let i = 0; i < subtitles.length; i++) {
    const raw = (subtitles[i] ?? "").replace(/\s+/g, " ").trim();
    if (!raw) continue;
    const dur = infos[i]?.duration || 0;
    if (dur <= 0) continue;
    // Show text over the stable middle of the clip, clear of the fades.
    const pad = infos.length > 1 ? Math.min(0.25, t) : 0;
    const from = starts[i] + pad;
    const to = Math.max(from + 0.4, starts[i] + dur - pad);
    cues.push(`${idx}\n${srtTime(from)} --> ${srtTime(to)}\n${wrapSubtitle(raw)}\n`);
    idx++;
  }
  return cues.join("\n");
}

/**
 * Burn an SRT into a video. Runs with cwd=workDir and a bare filename so the
 * subtitles filter never has to escape ':' / '/' in an absolute path.
 * Video is re-encoded; audio is stream-copied. Returns the output path.
 */
async function burnSubtitles(inputPath: string, srtName: string, outPath: string, workDir: string, styleOverride?: string): Promise<void> {
  const style =
    styleOverride ??
    "FontName=DejaVu Sans,Fontsize=15,PrimaryColour=&H00FFFFFF,OutlineColour=&H00000000," +
    "BorderStyle=1,Outline=2,Shadow=1,Alignment=2,MarginV=64";
  await runFfmpeg(
    [
      "-i", inputPath,
      "-vf", `subtitles=${srtName}:force_style='${style}'`,
      "-c:v", "libx264", "-preset", "veryfast", "-crf", "20", "-pix_fmt", "yuv420p",
      "-c:a", "copy",
      "-movflags", "+faststart",
      outPath,
    ],
    "burn subtitles",
    { cwd: workDir }
  );
}

/**
 * Stage 4 — burn per-line subtitles into ONE scene clip right after generation.
 *
 * `lines` are the scene's dialogue lines (story language) in speaking order; each line is shown
 * for a share of the clip proportional to its word count (speech fills the whole clip, so the
 * cues follow the rhythm closely enough without a word-level alignment). Returns the mp4 buffer.
 */
export async function burnSceneSubtitles(videoUrl: string, lines: string[]): Promise<Buffer> {
  const clean = lines.map((l) => l.replace(/\s+/g, " ").trim()).filter(Boolean);
  if (!clean.length) throw new Error("no subtitle lines");
  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), "scene-subs-"));
  try {
    const src = path.join(workDir, "src.mp4");
    await downloadToFile(videoUrl, src);
    const info = await probeMedia(src);
    if (!info.hasVideo || info.duration <= 0) throw new Error("source clip unreadable");
    const lead = 0.3; // speech starts almost immediately; keep the text off the very first frames
    const usable = Math.max(1, info.duration - lead - 0.2);
    const weights = clean.map((l) => Math.max(1, l.split(" ").length));
    const total = weights.reduce((a, b) => a + b, 0);
    let t = lead;
    const cues = clean.map((text, i) => {
      const from = t;
      const to = i === clean.length - 1 ? lead + usable : from + (usable * weights[i]) / total;
      t = to;
      return `${i + 1}\n${srtTime(from)} --> ${srtTime(Math.max(from + 0.4, to))}\n${wrapSubtitle(text, 32)}\n`;
    });
    await fs.writeFile(path.join(workDir, "subs.srt"), cues.join("\n"), "utf8");
    const out = path.join(workDir, "out.mp4");
    // Vertical 9:16 clip: libass scales Fontsize against a 288-line canvas, so 9 ≈ 3% of the frame
    // height — readable on a phone without covering the faces; MarginV keeps it in the bottom safe area.
    const style =
      "FontName=DejaVu Sans,Fontsize=9,PrimaryColour=&H00FFFFFF,OutlineColour=&H00000000," +
      "BorderStyle=1,Outline=1,Shadow=1,Alignment=2,MarginV=34";
    await burnSubtitles(src, "subs.srt", out, workDir, style);
    return await fs.readFile(out);
  } finally {
    await fs.rm(workDir, { recursive: true, force: true }).catch(() => {});
  }
}

export interface AssembleResult {
  /** Path to the assembled mp4 (inside `workDir`). */
  outputPath: string;
  /** Temp directory holding all intermediates — remove when done. */
  workDir: string;
  /** Per-scene audio source actually used, for logging/diagnostics. */
  audioSources: Array<"voiceover" | "native" | "silence">;
  info: MediaInfo;
}

/**
 * Build one uniform clip: video stream copied, audio always present as AAC 44.1kHz stereo.
 * - voiceover present  → mux the voiceover (clip's native audio, if any, is ignored)
 * - no voiceover       → keep native audio if the clip has one, else add a silent track
 * Audio is trimmed to the video length so scene timing stays intact.
 */
async function normalizeClip(
  videoPath: string,
  audioPath: string | null,
  outPath: string
): Promise<"voiceover" | "native" | "silence"> {
  const audioArgs = ["-c:a", "aac", "-b:a", "192k", "-ar", "44100", "-ac", "2"];
  const info = await probeMedia(videoPath);
  // Clip length is dictated by the VIDEO: a shorter voiceover is padded with silence
  // (`apad`), a longer one is cut at the video end (`-t`). Never `-shortest` alone — it
  // would truncate the video to a short voiceover.
  const lengthArgs = info.duration > 0 ? ["-t", info.duration.toFixed(3)] : ["-shortest"];

  if (audioPath) {
    await runFfmpeg(
      [
        "-i", videoPath,
        "-i", audioPath,
        "-map", "0:v:0", "-map", "1:a:0",
        "-af", "apad",
        "-c:v", "copy", ...audioArgs,
        ...lengthArgs,
        "-movflags", "+faststart",
        outPath,
      ],
      "mux voiceover"
    );
    return "voiceover";
  }

  if (info.hasAudio) {
    await runFfmpeg(
      ["-i", videoPath, "-map", "0:v:0", "-map", "0:a:0", "-c:v", "copy", ...audioArgs, "-movflags", "+faststart", outPath],
      "normalize native audio"
    );
    return "native";
  }

  await runFfmpeg(
    [
      "-i", videoPath,
      "-f", "lavfi", "-i", "anullsrc=channel_layout=stereo:sample_rate=44100",
      "-map", "0:v:0", "-map", "1:a:0",
      "-c:v", "copy", ...audioArgs,
      "-shortest",
      "-movflags", "+faststart",
      outPath,
    ],
    "add silent track"
  );
  return "silence";
}

/**
 * Blend length between consecutive shots, in seconds. Kept SHORT (a match-cut, not an
 * obvious dissolve): with frame-chaining the last frame of one clip already matches the
 * first frame of the next, so a tiny 0.2s blend hides the seam and the episode reads as
 * one continuous take rather than a slideshow of dissolves.
 */
export const TRANSITION_SEC = 0.2;

/**
 * Join uniform clips with smooth dissolves: N clips → N-1 chained `xfade=transition=fade`
 * filters on video and matching `acrossfade` filters on audio. Every input is first
 * normalized to the geometry / frame rate of the first clip (xfade requires identical
 * size, fps and timebase). Each transition overlaps the clips by `fade` seconds, so the
 * k-th transition starts at `sum(d_0..d_{k-1}) - k * fade`.
 */
async function crossfadeClips(
  clips: string[],
  infos: MediaInfo[],
  outPath: string,
  fade: number
): Promise<void> {
  const n = clips.length;
  const ref = infos[0];
  const w = ref.width || 720;
  const h = ref.height || 1280;
  const fps = ref.fps > 0 ? Math.round(ref.fps) : 24;

  // Never let a transition eat more than half of the shortest shot.
  const minDur = Math.min(...infos.map((i) => i.duration).filter((d) => d > 0));
  const d = Math.max(0.1, Math.min(fade, (Number.isFinite(minDur) ? minDur : fade) / 2));

  const parts: string[] = [];
  for (let i = 0; i < n; i++) {
    parts.push(
      `[${i}:v:0]scale=${w}:${h}:force_original_aspect_ratio=decrease,` +
        `pad=${w}:${h}:(ow-iw)/2:(oh-ih)/2,setsar=1,fps=${fps},format=yuv420p,settb=AVTB[v${i}]`
    );
    parts.push(`[${i}:a:0]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo,asetpts=PTS-STARTPTS[a${i}]`);
  }

  let vPrev = "v0";
  let aPrev = "a0";
  let elapsed = infos[0].duration;
  for (let i = 1; i < n; i++) {
    const offset = Math.max(0, elapsed - d);
    const vOut = i === n - 1 ? "vout" : `vx${i}`;
    const aOut = i === n - 1 ? "aout" : `ax${i}`;
    parts.push(`[${vPrev}][v${i}]xfade=transition=fade:duration=${d.toFixed(3)}:offset=${offset.toFixed(3)}[${vOut}]`);
    parts.push(`[${aPrev}][a${i}]acrossfade=d=${d.toFixed(3)}:c1=tri:c2=tri[${aOut}]`);
    vPrev = vOut;
    aPrev = aOut;
    elapsed = elapsed + infos[i].duration - d;
  }

  await runFfmpeg(
    [
      ...clips.flatMap((c) => ["-i", c]),
      "-filter_complex", parts.join(";"),
      "-map", "[vout]", "-map", "[aout]",
      "-c:v", "libx264", "-preset", "veryfast", "-crf", "20", "-pix_fmt", "yuv420p", "-r", String(fps),
      "-c:a", "aac", "-b:a", "192k", "-ar", "44100", "-ac", "2",
      "-movflags", "+faststart",
      outPath,
    ],
    "xfade crossfade"
  );
}

/**
 * Fallback: hard-cut concatenation of uniform clips. First try a lossless stream copy;
 * if that fails, re-encode via the concat filter.
 */
async function concatClips(clips: string[], workDir: string, outPath: string): Promise<void> {
  const listPath = path.join(workDir, "concat.txt");
  const escape = (p: string) => p.replace(/'/g, "'\\''");
  await fs.writeFile(listPath, clips.map((c) => `file '${escape(c)}'`).join("\n") + "\n");

  try {
    await runFfmpeg(
      ["-f", "concat", "-safe", "0", "-i", listPath, "-map", "0:v:0", "-map", "0:a:0", "-c", "copy", "-movflags", "+faststart", outPath],
      "concat (copy)"
    );
    const info = await probeMedia(outPath);
    if (info.hasVideo && info.hasAudio) return;
    console.warn("[ffmpeg] concat copy produced no audio/video stream — re-encoding");
  } catch (err) {
    console.warn("[ffmpeg] concat copy failed — re-encoding:", (err as Error).message);
  }

  const inputs = clips.flatMap((c) => ["-i", c]);
  const filter =
    clips.map((_, i) => `[${i}:v:0][${i}:a:0]`).join("") + `concat=n=${clips.length}:v=1:a=1[v][a]`;
  await runFfmpeg(
    [
      ...inputs,
      "-filter_complex", filter,
      "-map", "[v]", "-map", "[a]",
      "-c:v", "libx264", "-preset", "veryfast", "-crf", "20", "-pix_fmt", "yuv420p",
      "-c:a", "aac", "-b:a", "192k", "-ar", "44100", "-ac", "2",
      "-movflags", "+faststart",
      outPath,
    ],
    "concat (re-encode)"
  );
}

/**
 * Download all scene clips (+ voiceovers), give every clip a uniform audio track and
 * join them in order with dissolve transitions. Caller must `fs.rm(result.workDir, { recursive: true })`.
 */
export async function assembleEpisodeLocally(scenes: SceneClipInput[]): Promise<AssembleResult> {
  if (scenes.length === 0) throw new Error("No scenes to assemble");
  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), "episode-"));

  const audioSources: AssembleResult["audioSources"] = [];
  const normalized: string[] = [];

  for (let i = 0; i < scenes.length; i++) {
    const s = scenes[i];
    const idx = String(i + 1).padStart(3, "0");
    const videoPath = path.join(workDir, `scene_${idx}.mp4`);
    await downloadToFile(s.videoUrl, videoPath);

    let audioPath: string | null = null;
    if (s.audioUrl) {
      audioPath = path.join(workDir, `scene_${idx}_voice.audio`);
      await downloadToFile(s.audioUrl, audioPath);
    }

    const outPath = path.join(workDir, `clip_${idx}.mp4`);
    audioSources.push(await normalizeClip(videoPath, audioPath, outPath));
    normalized.push(outPath);

    // Free disk early — /tmp on serverless is limited.
    await fs.rm(videoPath, { force: true });
    if (audioPath) await fs.rm(audioPath, { force: true });
  }

  // Probe every normalized clip up-front — needed both for the crossfade math and for
  // timing the burned-in subtitles to each clip's position on the final timeline.
  const infos = await Promise.all(normalized.map((c) => probeMedia(c)));

  const joinedPath = path.join(workDir, "joined.mp4");
  if (normalized.length === 1) {
    await fs.copyFile(normalized[0], joinedPath);
  } else {
    try {
      await crossfadeClips(normalized, infos, joinedPath, TRANSITION_SEC);
    } catch (err) {
      // Crossfade is best-effort: never fail the whole assembly because of a transition.
      console.warn("[ffmpeg] xfade failed — falling back to hard cuts:", (err as Error).message);
      await fs.rm(joinedPath, { force: true });
      await concatClips(normalized, workDir, joinedPath);
    }
  }

  // Burn per-scene subtitles (timed to each clip's segment). Always on — the assembled
  // episode should read like a finished film. Best-effort: keep the video if it fails.
  const outputPath = path.join(workDir, "episode.mp4");
  const hasSubs = scenes.some((s) => (s.subtitle ?? "").trim());
  if (hasSubs) {
    try {
      const srt = buildSrt(scenes.map((s) => s.subtitle), infos, TRANSITION_SEC);
      const srtName = "subs.srt";
      await fs.writeFile(path.join(workDir, srtName), srt, "utf8");
      await burnSubtitles(joinedPath, srtName, outputPath, workDir);
    } catch (err) {
      console.warn("[ffmpeg] subtitle burn failed — using video without subtitles:", (err as Error).message);
      await fs.rm(outputPath, { force: true }).catch(() => {});
      await fs.copyFile(joinedPath, outputPath);
    }
  } else {
    await fs.copyFile(joinedPath, outputPath);
  }
  await fs.rm(joinedPath, { force: true }).catch(() => {});

  const info = await probeMedia(outputPath);
  if (!info.hasVideo) throw new Error("Assembled episode has no video stream");
  if (!info.hasAudio) throw new Error("Assembled episode has no audio stream");

  return { outputPath, workDir, audioSources, info };
}
