/**
 * Power tier — the single source of truth for what the project's "мощность"
 * really controls in the video pipeline.
 *
 * Honest scope (verified against the real Seedance 2.5 schema on Replicate):
 *   - resolution: only "480p" | "720p" exist for Seedance 2.5 (no 1080p)
 *   - baseDuration: the minimal clip length the tier pays for (seconds);
 *     actual clip length is clamped by the scene rules in the video routes
 *   - costPerScene: credits charged per scene clip at baseDuration
 *
 * Anything else (audio, aspect ratio, model) is identical across tiers.
 * Stage 2 must read from here instead of hard-coding numbers.
 */

export type PowerTier = "LOW" | "MEDIUM" | "HIGH";

export const POWER_TIERS: readonly PowerTier[] = ["LOW", "MEDIUM", "HIGH"];

export type SeedanceResolution = "480p" | "720p";

/** Real Seedance 2.5 schema on Replicate: duration integer 1–30 s (verified 2026-09). Same for every tier. */
export const SEEDANCE_MAX_DURATION = 30;

export interface PowerTierConfig {
  id: PowerTier;
  /** Legacy Project.tier value kept in sync for older code paths / dashboard. */
  legacyTier: "minimum" | "medium" | "maximum";
  label: string;
  /** Short UI description (RU) — quality / cost. */
  description: string;
  resolution: SeedanceResolution;
  /** Seconds of clip the base cost covers. */
  baseDuration: number;
  /** Credits per scene clip at baseDuration. */
  costPerScene: number;
  /** Longest clip the tier may request from the model (seconds). */
  maxDuration: number;
}

export const POWER_TIER_CONFIG: Record<PowerTier, PowerTierConfig> = {
  LOW: {
    id: "LOW",
    legacyTier: "minimum",
    label: "480p",
    description: "Draft quality — quick tests and previews, the lowest price.",
    resolution: "480p",
    baseDuration: 5,
    costPerScene: 1,
    maxDuration: SEEDANCE_MAX_DURATION,
  },
  MEDIUM: {
    id: "MEDIUM",
    legacyTier: "medium",
    label: "720p",
    description: "Full Seedance 2.5 quality (the model's maximum) — for the finished series.",
    resolution: "720p",
    baseDuration: 5,
    costPerScene: 3,
    maxDuration: SEEDANCE_MAX_DURATION,
  },
  HIGH: {
    id: "HIGH",
    legacyTier: "maximum",
    label: "720p+",
    description: "720p with an extended per-scene budget (legacy projects only).",
    resolution: "720p",
    baseDuration: 10,
    costPerScene: 8,
    maxDuration: SEEDANCE_MAX_DURATION,
  },
};

export const DEFAULT_POWER_TIER: PowerTier = "MEDIUM";

/**
 * Stage 46B — every scene clip is rendered at a FIXED 480p, whatever tier the project stores.
 * Quality is chosen only when the finished episode is assembled (see lib/ffmpeg.ts render options).
 * Scene pricing therefore always follows the 480p (LOW) config.
 */
export const SCENE_RESOLUTION: SeedanceResolution = "480p";

/** Effective per-scene config (Stage 46B): the stored tier id/label are kept, the render values are 480p. */
export function sceneTierConfig(cfg: PowerTierConfig): PowerTierConfig {
  const low = POWER_TIER_CONFIG.LOW;
  return { ...cfg, resolution: SCENE_RESOLUTION, baseDuration: low.baseDuration, costPerScene: low.costPerScene };
}

export function isPowerTier(value: unknown): value is PowerTier {
  return typeof value === "string" && (POWER_TIERS as readonly string[]).includes(value);
}

/** Map legacy Project.tier (minimum/medium/maximum) → power tier. */
export function legacyTierToPower(tier: string | null | undefined): PowerTier {
  switch (tier) {
    case "minimum":
      return "LOW";
    case "maximum":
      return "HIGH";
    case "medium":
      return "MEDIUM";
    default:
      return DEFAULT_POWER_TIER;
  }
}

export function powerToLegacyTier(power: PowerTier): PowerTierConfig["legacyTier"] {
  return POWER_TIER_CONFIG[power].legacyTier;
}

/**
 * Resolve the effective tier for a project. New projects carry `powerTier`;
 * legacy projects only have `tier` — both paths yield the same config.
 */
export function resolvePowerTier(project: {
  powerTier?: string | null;
  tier?: string | null;
}): PowerTierConfig {
  const power = isPowerTier(project.powerTier)
    ? project.powerTier
    : legacyTierToPower(project.tier);
  // Stage 46B: scenes are always 480p — the tier only survives as a stored id.
  return sceneTierConfig(POWER_TIER_CONFIG[power]);
}

/** Credits charged when a character reference is regenerated by prompt (stage 1). */
export const CHARACTER_REFERENCE_COST = 1;
