/**
 * Power tier — the single source of truth for what the project's "мощность"
 * really controls in the video pipeline.
 *
 * Honest scope (verified against the real Seedance 2.5 schema on WaveSpeed):
 *   - resolution: Seedance 2.5 tops out at "720p" (no 1080p); 480p was removed — every clip renders at 720p
 *   - baseDuration: the minimal clip length the tier pays for (seconds);
 *     actual clip length is clamped by the scene rules in the video routes
 *   - costPerScene: credits charged per scene clip at baseDuration
 *
 * Anything else (audio, aspect ratio, model) is identical across tiers.
 * Stage 2 must read from here instead of hard-coding numbers.
 */

export type PowerTier = "LOW" | "MEDIUM" | "HIGH";

export const POWER_TIERS: readonly PowerTier[] = ["LOW", "MEDIUM", "HIGH"];

export type SeedanceResolution = "720p";

/** Real Seedance 2.5 schema on WaveSpeed: duration integer 1–30 s (verified 2026-09). Same for every tier. */
export const SEEDANCE_MAX_DURATION = 30;

export interface PowerTierConfig {
  id: PowerTier;
  /** Legacy Project.tier value kept in sync for older code paths / dashboard. */
  legacyTier: "minimum" | "medium" | "maximum";
  label: string;
  /** Short UI description (RU) — quality / cost. */
  description: string;
  resolution: SeedanceResolution;
  /** Seconds of clip the base cost covers. */
  baseDuration: number;
  /** Credits per scene clip at baseDuration. */
  costPerScene: number;
  /** Longest clip the tier may request from the model (seconds). */
  maxDuration: number;
}

export const POWER_TIER_CONFIG: Record<PowerTier, PowerTierConfig> = {
  LOW: {
    id: "LOW",
    legacyTier: "minimum",
    label: "720p",
    description: "Standard price tier — renders at full Seedance 2.5 quality (720p) like every other tier.",
    resolution: "720p",
    baseDuration: 5,
    // Pricing model: 10 credits = 1 second of video. baseDuration=5 and costPerScene=50
    // make sceneClipCost() charge exactly 10 × clip length in seconds (5 s clip = 50 credits,
    // 10 s = 10 credits …). Every scene renders at this 480p (LOW) config (see sceneTierConfig),
    // so this is the effective per-second rate for ALL tiers.
    costPerScene: 50,
    maxDuration: SEEDANCE_MAX_DURATION,
  },
  MEDIUM: {
    id: "MEDIUM",
    legacyTier: "medium",
    label: "720p",
    description: "Full Seedance 2.5 quality (the model's maximum) — for the finished series.",
    resolution: "720p",
    baseDuration: 5,
    costPerScene: 30,
    maxDuration: SEEDANCE_MAX_DURATION,
  },
  HIGH: {
    id: "HIGH",
    legacyTier: "maximum",
    label: "720p+",
    description: "720p with an extended per-scene budget (legacy projects only).",
    resolution: "720p",
    baseDuration: 10,
    costPerScene: 80,
    maxDuration: SEEDANCE_MAX_DURATION,
  },
};

export const DEFAULT_POWER_TIER: PowerTier = "MEDIUM";

/**
 * Every scene clip is rendered at the model's MAXIMUM quality (720p for Seedance 2.5), whatever tier
 * the project stores — there is no quality choice and no 480p anywhere. Pricing follows the LOW config.
 */
export const SCENE_RESOLUTION: SeedanceResolution = "720p";

/** Effective per-scene config: the stored tier id/label are kept, the render resolution is always the max (720p). */
export function sceneTierConfig(cfg: PowerTierConfig): PowerTierConfig {
  const low = POWER_TIER_CONFIG.LOW;
  return { ...cfg, resolution: SCENE_RESOLUTION, baseDuration: low.baseDuration, costPerScene: low.costPerScene };
}

export function isPowerTier(value: unknown): value is PowerTier {
  return typeof value === "string" && (POWER_TIERS as readonly string[]).includes(value);
}

/** Map legacy Project.tier (minimum/medium/maximum) → power tier. */
export function legacyTierToPower(tier: string | null | undefined): PowerTier {
  switch (tier) {
    case "minimum":
      return "LOW";
    case "maximum":
      return "HIGH";
    case "medium":
      return "MEDIUM";
    default:
      return DEFAULT_POWER_TIER;
  }
}

export function powerToLegacyTier(power: PowerTier): PowerTierConfig["legacyTier"] {
  return POWER_TIER_CONFIG[power].legacyTier;
}

/**
 * Resolve the effective tier for a project. New projects carry `powerTier`;
 * legacy projects only have `tier` — both paths yield the same config.
 */
export function resolvePowerTier(project: {
  powerTier?: string | null;
  tier?: string | null;
}): PowerTierConfig {
  const power = isPowerTier(project.powerTier)
    ? project.powerTier
    : legacyTierToPower(project.tier);
  // Scenes always render at the model maximum (720p) — the tier only survives as a stored id.
  return sceneTierConfig(POWER_TIER_CONFIG[power]);
}

/** Credits charged when a character reference is regenerated by prompt (stage 1). */
export const CHARACTER_REFERENCE_COST = 10;
/** Stage 173: one location master set = a single wide establishing master (1 frame). Client-safe. */
export const LOCATION_MASTER_FRAMES = 1;
export const LOCATION_SET_COST = CHARACTER_REFERENCE_COST * LOCATION_MASTER_FRAMES;
