/**
 * Test mode: a one-minute "mini-trailer" — 3 scenes (≈ 30 + 20 + 30 s) that demonstrate the
 * product in miniature: real dialogue (5–7 sentences), an emotional turn, a transition between
 * two locations with locked lighting. Lets the author check the look without generating a season.
 */
import { z } from "zod";
import { LANGUAGE_NAMES, type IdeaLanguage, type CharacterCard } from "@/lib/idea";
import { sceneScriptSchema, TALK_MIN_SENTENCES, TALK_MAX_SENTENCES, SCENE_MAX_SECONDS, type LocationRef } from "@/lib/season";

export const TRAILER_SEASON_NUMBER = 0;
export const TRAILER_MIN_SCENES = 3;
export const TRAILER_MAX_SCENES = 4;
export const TRAILER_JOB_TYPE = "trailer_script";

export const trailerScriptSchema = z.object({
  title: z.string().min(1),
  logline: z.string().min(10),
  visualIdentity: z.string().min(10),
  locationNames: z.array(z.string().min(1)).min(1).max(2),
  scenes: z.array(sceneScriptSchema).min(TRAILER_MIN_SCENES).max(TRAILER_MAX_SCENES),
});
export type TrailerScript = z.infer<typeof trailerScriptSchema>;

const langName = (l: IdeaLanguage) => LANGUAGE_NAMES[l] ?? "Russian";

export function trailerSystemPrompt(language: IdeaLanguage): string {
  const L = langName(language);
  return `You are a film director writing a ONE-MINUTE TEST MINI-TRAILER of a short-form VERTICAL drama (9:16), generated by an AI video model WITH native speech. It is a quick demo for the author: it must show, in ${TRAILER_MIN_SCENES} shots (max ${TRAILER_MAX_SCENES}), everything the full series will do — real dialogue, an emotional turn, a change of location, expressive faces.

Return STRICT JSON: {"title": string, "logline": string, "visualIdentity": string, "locationNames": [1-2 names], "scenes": [{"number": int, "shotType": string, "durationSec": int, "locationDesc": string, "characters": [names], "action": string, "dialogue": string, "videoPrompt": string}]}.

HARD RULES:
T1. Exactly 3 scenes by default: (1) ${SCENE_MAX_SECONDS}s — medium shot in LOCATION A, two MAIN characters in a substantive exchange of ${TALK_MIN_SENTENCES}–${TALK_MAX_SENTENCES} full sentences (3–5 lines, they answer each other); (2) 20s — close-up/over-the-shoulder in the SAME location from a different angle: an emotional turn (anger → tears, calm → threat) with 3–5 sentences; (3) ${SCENE_MAX_SECONDS}s — LOCATION B (a different listed location), a third character or a crowd joins, ${TALK_MIN_SENTENCES}–${TALK_MAX_SENTENCES} sentences ending on a hook. No silent scenes. Total ≈ 60–80 seconds.
T2. Dialogue format: one line per row, NAME (tone cue): "line", in ${L}. Only real spoken lines — the story is told through the dialogue.
T3. "videoPrompt" is ENGLISH with EXACTLY these 9 tagged lines in this order: [SHOT TYPE], [VISUAL STYLE] (the visualIdentity sentence, identical in all scenes), [LIGHTING] (identical wording within one location — the camera moves, the light does not), [BLOCKING], [GAZE], [NON-VERBAL], [ACTION], [CHARACTER] (every visible character: name, age, hair, skin, build, exact clothing — identical in every scene), [TRANSITION]. No spoken text inside the videoPrompt.
T4. "locationNames" are copied VERBATIM from the given LOCATIONS list (they already have reference images); scene "locationDesc" is "INT/EXT — place — time of day" in ${L} and starts with the location name. Use ONLY the given character names.
T5. Original content only — never reuse names, plots or lines of existing films/series. "title"/"logline" in ${L}, short.`;
}

export function trailerUserPrompt(synopsis: string, characters: CharacterCard[], locations: LocationRef[]): string {
  const cast = characters.map((c) => `- ${c.name}${c.tier ? ` [${c.tier}]` : ""}${c.role ? ` — ${c.role}` : ""}${c.appearance ? `: ${c.appearance}` : ""}`).join("\n");
  const locs = locations.length ? locations.map((l) => `- ${l.name}${l.description ? ` — ${l.description}` : ""}`).join("\n") : "(none — invent two places)";
  return `SYNOPSIS:\n${synopsis}\n\nCHARACTERS:\n${cast}\n\nLOCATIONS (copy names verbatim):\n${locs}`;
}
